apiVersion: apps/v1
kind: Deployment
metadata:
<<<<<<< HEAD
  name: newserver
=======
  name: marketingserver
>>>>>>> master
spec:
  replicas: 5
  selector:
    matchLabels:
<<<<<<< HEAD
      app: newserver
  template:
    metadata:
      labels:
        app: newserver
    spec:
      containers:
      - name: newserver
        image: mickeydoe/mike_portfolio:v2.0.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
=======
      app: marketingserver
  template:
    metadata:
      labels:
        app: marketingserver
    spec:
      containers:
      - name: marketingserver
        image: mickeydoe/marketingwebsite
        resources:
>>>>>>> master
        ports:
        - containerPort: 80
