apiVersion: v1
kind: Service
metadata:
<<<<<<< HEAD
  name: newserver
spec:
  type: LoadBalancer
  selector:
    app: newserver
=======
  name: marketingserver
spec:
  type: LoadBalancer
  selector:
    app: marketingserver
>>>>>>> master
  ports:
  - port: 6060
    targetPort: 80
